#! /bin/bash

# el argumento es <miniconda>/lib/pythonX.X

# p.ej.:

# bash install_tex_fonts /home/brutus/apps/miniconda/lib/python3.6/

# El único método que he conseguido para instalar el tipo de letra bonito en las ecuaciones
# es el siguiente, que consiste en "engañar" a jupyter cambiando el nombre del directorio.

cd $1/site-packages/notebook/static/components/MathJax

# Descargamos las fonts

svn export https://github.com/mathjax/MathJax/trunk/fonts/HTML-CSS/TeX/woff fonts/HTML-CSS/TeX/woff
svn export https://github.com/mathjax/MathJax/trunk/jax/output/HTML-CSS/fonts/TeX jax/output/HTML-CSS/fonts/TeX

# renombramos los directorios

mv fonts/HTML-CSS/STIX-Web fonts/HTML-CSS/True-STIX-Web
mv fonts/HTML-CSS/TeX fonts/HTML-CSS/STIX-Web

mv jax/output/HTML-CSS/fonts/STIX-Web jax/output/HTML-CSS/fonts/True-STIX-Web
mv jax/output/HTML-CSS/fonts/TeX jax/output/HTML-CSS/fonts/STIX-Web

